### ISSUE TITLE
where should i put into ~/.config/smallwm it's a folder or a file ???

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [adamnew123456/SmallWM#10]
what in $HOME

**Comment by soyDESKTOP68A2MRFT** [comment]
i say it because of is not clear to me what is the name of the file which is in ~/.config/smallwm

**Comment by soyDESKTOP68A2MRFT** [comment]
or is ~/.config/_**smallwm**_ (the bolded and italic part is the part which confuse me) a file ????

**Comment by soyDESKTOP68A2MRFT** [comment]
mean if _**smallwm**_  is a file

**Comment by soyDESKTOP68A2MRFT** [comment]
or a folder

**Comment by soyDESKTOP68A2MRFT** [comment]
what it  is

**Comment by soyDESKTOP68A2MRFT** [comment]
it's confusing to me

**Comment by soyDESKTOP68A2MRFT** [comment]
because i know that smallwmrc is a file because of the "rc" part but is not clear FOR ME if ~/.config/smallwm is a file or a folder

**Comment by adamnew123456** [comment]
The lack of extension is kind of weird (I'd call it _smallwm.conf_ these days), but it is a file:

```
$ cat ~/.config/smallwm
[smallwm]
shell=/usr/bin/urxvt
desktops=5
border-width=2 
icon-height=24
icon-width=120
icon-icons=0
hotkey-mode=focus
[keyboard]
exit=p
```

**Comment by soyDESKTOP68A2MRFT** [comment]
thanks
