### ISSUE TITLE
how can i make the text of the icons bigger

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [adamnew123456/SmallWM#12]
i mean the text which appears when you hide the windows with Super+h so there appears a text in that "icon" so how can i make that text bigger through the ~/.config/smallwm file ????

**Comment by soyDESKTOP68A2MRFT** [comment]
and have smallwm support for themes ??? where could i find some themes ????

**Comment by adamnew123456** [comment]
There's not a way to configure colors and fonts, I didn't get far into the colormap and font APIs. If you're interested I would look at the docs for [colormaps](https://tronche.com/gui/x/xlib/color/) and [font loading](https://tronche.com/gui/x/xlib/graphics/font-metrics/), if you can get those resources from X then you can [load them to the graphics context](https://tronche.com/gui/x/xlib/GC/manipulating.html) when the icons or window borders are drawn.
